language: node_js
install:
- npm install -g gulp-cli bower
- bower install
- npm install
script:
- gulp build
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master